let orderData = [
	{
		order_id:123455666,
		order_state:"待支付",
		order_title:"墙面修复翻新",
		order_appointment:"2023-7-20",
		order_address:"成都市武侯区理想中心",
		order_price:"¥80/1平米起",
		order_beforeTime:"2022-10-1",
		order_descript:"水龙头坏了",
		order_createTime:"2023-7-20 17:50",
		order_imgList:[
			"../../../static/imgs/售后.png",
			"../../../static/imgs/售后.png",
			"../../../static/imgs/售后.png",
			"../../../static/imgs/售后.png"
		],
		order_master:{
			avatar:"../../../static/imgs/头像.png",
			name:"张师傅",
			stars:4,
			introduce:"好人好人",
			telephone:"12345678910"
			
		}
	},
	{
		order_id:480014,
		order_state:"待上门",
		order_title:"墙面修复翻新",
		order_appointment:"2023-7-20",
		order_address:"成都市武侯区理想中心",
		order_price:"¥80/1平米起",
		order_beforeTime:"2022-10-1",
		order_descript:"水龙头坏了",
		order_createTime:"2023-7-20 17:50",
		order_imgList:[
			"../../../static/imgs/售后.png",
			"../../../static/imgs/售后.png",
			"../../../static/imgs/售后.png",
			"../../../static/imgs/售后.png"
		],
		order_master:{
			avatar:"../../../static/imgs/头像.png",
			name:"刘师傅",
			stars:4,
			introduce:"好人好人",
			telephone:"12345678910"
			
		}
	},
	{
		order_id:240104,
		order_state:"进行中",
		order_title:"墙面修复翻新",
		order_appointment:"2023-7-20",
		order_address:"成都市武侯区理想中心",
		order_price:"¥80/1平米起",
		order_beforeTime:"2022-10-1",
		order_descript:"水龙头坏了",
		order_createTime:"2023-7-20 17:50",
		order_imgList:[
			"../../../static/imgs/售后.png",
			"../../../static/imgs/售后.png",
			"../../../static/imgs/售后.png",
			"../../../static/imgs/售后.png"
		],
		order_master:{
			avatar:"../../../static/imgs/头像.png",
			name:"唐师傅",
			stars:4,
			introduce:"好人好人",
			telephone:"12345678910"
			
		}
	},
	{
		order_id:209024,
		order_state:"待评价",
		order_title:"墙面修复翻新",
		order_appointment:"2023-7-20",
		order_address:"成都市武侯区理想中心",
		order_price:"¥80/1平米起",
		order_beforeTime:"2022-10-1",
		order_descript:"水龙头坏了",
		order_createTime:"2023-7-20 17:50",
		order_imgList:[
			"../../../static/imgs/售后.png",
			"../../../static/imgs/售后.png",
			"../../../static/imgs/售后.png",
			"../../../static/imgs/售后.png"
		],
		order_master:{
			avatar:"../../../static/imgs/头像.png",
			name:"汪师傅",
			stars:4,
			introduce:"好人好人",
			telephone:"12345678910"
			
		}
	},
	{
		order_id:79279472914,
		order_state:"已完成",
		order_title:"墙面修复翻新",
		order_appointment:"2023-7-20",
		order_address:"成都市武侯区理想中心",
		order_price:"¥80/1平米起",
		order_beforeTime:"2022-10-1",
		order_descript:"水龙头坏了",
		order_createTime:"2023-7-20 17:50",
		order_imgList:[
			"../../../static/imgs/售后.png",
			"../../../static/imgs/售后.png",
			"../../../static/imgs/售后.png",
			"../../../static/imgs/售后.png"
		],
		order_master:{
			avatar:"../../../static/imgs/头像.png",
			name:"陈师傅",
			stars:4,
			introduce:"好人好人",
			telephone:"12345678910"
			
		}
	},
	{
		order_id:839247934,
		order_state:"待支付",
		order_title:"墙面修复翻新",
		order_appointment:"2023-7-20",
		order_address:"成都市武侯区理想中心",
		order_price:"¥80/1平米起",
		order_beforeTime:"2022-10-1",
		order_descript:"水龙头坏了",
		order_imgList:[
			"../../../static/imgs/售后.png",
			"../../../static/imgs/售后.png",
			"../../../static/imgs/售后.png",
			"../../../static/imgs/售后.png"
		],
		order_master:{
			avatar:"../../../static/imgs/头像.png",
			name:"王师傅",
			stars:4,
			introduce:"好人好人",
			telephone:"12345678910"
			
		}
	},
	{
		order_id:2489843,
		order_state:"已完成",
		order_title:"墙面修复翻新",
		order_appointment:"2023-7-20",
		order_address:"成都市武侯区理想中心",
		order_price:"¥80/1平米起",
		order_beforeTime:"2022-10-1",
		order_descript:"水龙头坏了",
		order_createTime:"2023-7-20 17:50",
		order_imgList:[
			"../../../static/imgs/售后.png",
			"../../../static/imgs/售后.png",
			"../../../static/imgs/售后.png",
			"../../../static/imgs/售后.png"
		],
		order_master:{
			avatar:"../../../static/imgs/头像.png",
			name:"李师傅",
			stars:4,
			introduce:"好人好人",
			telephone:"12345678910"
			
		}
	},
]
module.exports = {
	orderData
}